osd-bar=no # remove weird bar when using arrow keys
keep-open=yes # keep open after vid finishes

alang=ja,jpn,jp # audio lang
slang=en,eng # sub lang
sub-auto=fuzzy # external subs don't have to match the file name to autoload
